---
title: "🚀 Tasks"
musterloesung: false
---

:::{.callout-important}
Due date for the tasks are listed in @tbl-schedule
:::

## Task 1 





## Task 2 {#sec-vec-basic}

1. Download the datasets [swissTLM3D](https://www.swisstopo.admin.ch/en/landscape-model-swisstlm3d) and [swissboundaries3d](https://www.swisstopo.admin.ch/en/landscape-model-swissboundaries3d) from swisstopo.
2. Add the datasets to the local folder you created above, in a subfolder named `data`
3. Add the data folder to the `.gitignore` file.
4. In `index.qmd`, add a code chunk (R or Python) and solve the following tasks using your preferred language.
5. Using `swissTLM3d` and `swissboundaries3d`, calculate the percentage of area covered by forest *per canton*
6. Visualize the results (in a map and / or a plot)
7. Render the document using `quarto preview`
8. Publish your result using `quarto publish gh-pages`


A code chunk is added in the following manner. Please consult the [Quarto - Getting Started](https://quarto.org/docs/get-started/) for more information on your local setup.

````{.markdown filename="index.qmd"}
# Solution for Week1: Vector data processing
   
In this document, I solve the tasks for week 1 of the course 
*Spatiotemporal Datascience*

```{{r}}
library(sf)

```

````

::::{.content-hidden unless-meta="musterloesung"}

## Sample Solution

::: {.panel-tabset}

## R

```{r}
#| eval: false


{{< include _week-1-solution.R >}}
```


:::
::::



