project:
  type: website
  output-dir: _site

website:
  title: "Spatiotemporal Datascience"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Syllabus
        href: syllabus.qmd
      - text: Submission
        href: submission.qmd
      - text: Slides
        href: slides.qmd
      - text: Tasks
        href: tasks.qmd

format:
  revealjs-clean:
    smaller: true
    slide-number: c/t

bibliography: auxilliary/references.bib
execute:
  warning: false
  message: false
  echo: true
freeze: true
