project:
  type: website
  output-dir: _site

website:
  title: "Spatiotemporal Datascience"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Syllabus
        href: syllabus.qmd
      - text: Submission
        href: submission.qmd
      - text: Slides + Tasks
        href: slides-tasks.qmd

format:
  revealjs-clean:
    smaller: true
    slide-number: c/t
    logo: images/zhaw_rgb.png
    css:
      - auxilliary/style.css
      - auxilliary/style-terminal.css
    code-line-numbers: false
    highlight-style: atom-one

bibliography: auxilliary/references.bib
execute:
  warning: false
  message: false
  echo: true
freeze: true
